"use client";

import "./global.css"; // 导入全局样式文件 同时构建tailwind.css

import { AntdRegistry } from "@ant-design/nextjs-registry";
import store from "@/store/store";
import { Provider } from "react-redux";
// 根layout，包含antd的全局样式
export default function RootLayout({ children, params: { locale } }) {
  return (
    <html>
      <body>
        <Provider store={store}>
          <AntdRegistry>{children}</AntdRegistry>
        </Provider>
      </body>
    </html>
  );
}

// export const metadata = {
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // 设置 favicon 的路径
  },
};
